export enum Topic {
  ApellidoDeInformacionPersonalActualizado = 'libreta.usuarios.apellido-de-informacion-personal-actualizado',
  EmailDeUsuarioActualizado = 'libreta.usuarios.email-de-usuario-actualizado',
  EmailUnicoValidado = 'libreta.usuarios.email-unico-de-usuario-validado',
  InformacionPersonalBorrada = 'libreta.usuarios.informacion-personal-borrada',
  InformacionPersonalCreada = 'libreta.usuarios.informacion-personal-creada',
  InformacionPersonalEncontradaPorApellido = 'libreta.usuarios.informacion-personal-encontrada-por-apellido',
  InformacionPersonalEncontradaPorInformacionPersonalId = 'libreta.usuarios.informacion-personal-encontrada-por-informacion-personal-id',
  InformacionPersonalEncontradaPorNombre = 'libreta.usuarios.informacion-personal-encontrada-por-nombre',
  InformacionPersonalEncontradaPorUsuarioId = 'libreta.usuarios.informacion-personal-encontrada-por-usuario-id',
  NombreDeInformacionPersonalActualizado = 'libreta.usuarios.nombre-de-informacion-personal-actualizado',
  PasswordDeUsuarioActualizado = 'libreta.usuarios.password-de-usuario-actualizado',
  UsuarioBorrado = 'libreta.usuarios.usuario-borrado',
  UsuarioEncontradoPorEmailYPassword = 'libreta.usuarios.usuario-encontrado-por-email-y-password',
  UsuarioEncontradoPorEmail = 'libreta.usuarios.usuario-encontrado-por-email',
  UsuarioEncontradoPorUsuarioId = 'libreta.usuarios.usuario-encontrado-por-usuario-id',
  UsuarioCreado = 'libreta.usuarios.usuario-creado',
}
